// OneShot seed — populate 10 earbuds products.
// Run with: bun run db:push && bun run prisma db seed (or `bun run seed`).
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedProduct = {
  slug: string;
  name: string;
  tagline: string;
  title: string;
  price: number; // rupees
  compareAt?: number;
  productType: string;
  category: string;
  colorName: string;
  colorHex: string;
  imageKey: string;
  badge?: string;
  bullets: string[];
  description: string;
  features: string[];
  specs: [string, string][];
  rating: number;
  reviewCount: number;
  inStock: boolean;
};

const products: SeedProduct[] = [
  {
    slug: "airbuds",
    name: "OneShot AirBuds",
    tagline: "Lightweight everyday wireless earbuds",
    title:
      "OneShot AirBuds True Wireless Earbuds, Lightweight Design, Bluetooth 5.3, Stereo Sound, All-Day Comfort",
    price: 999,
    compareAt: 1499,
    productType: "Earbuds",
    category: "Everyday",
    colorName: "Cloud White",
    colorHex: "#f3f3f3",
    imageKey: "airbuds",
    badge: "BEST VALUE",
    bullets: [
      "Lightweight ergonomic design for all-day comfort",
      "Stable Bluetooth 5.3 connectivity with quick pairing",
      "Balanced stereo sound for music and calls",
      "Pocket-friendly charging case for easy portability",
      "Ideal for daily casual listening",
    ],
    description:
      "AirBuds are built for everyday listening. A lightweight shell, quick Bluetooth 5.3 pairing, and balanced stereo sound make them the easy choice for commutes, walks, and casual sessions.",
    features: [
      "Bluetooth 5.3",
      "Up to 24h total battery",
      "Touch controls",
      "IPX4 splash resistance",
    ],
    specs: [
      ["Driver", "10mm dynamic"],
      ["Battery (buds)", "5h playback"],
      ["Battery (case)", "24h total"],
      ["Charging", "USB-C"],
      ["Weight", "4.2g per bud"],
      ["Connectivity", "Bluetooth 5.3"],
    ],
    rating: 4.4,
    reviewCount: 1284,
    inStock: true,
  },
  {
    slug: "neopods",
    name: "OneShot NeoPods",
    tagline: "Compact, fast-pairing earbuds for daily use",
    title:
      "OneShot NeoPods Wireless Earbuds, Fast Pairing Bluetooth 5.3, HD Sound, Compact Design for Everyday Use",
    price: 1299,
    compareAt: 1899,
    productType: "Earbuds",
    category: "Everyday",
    colorName: "Midnight Black",
    colorHex: "#1a1a1a",
    imageKey: "neopods",
    bullets: [
      "Fast auto-pairing for instant connection",
      "Clear HD stereo audio output",
      "Compact and stylish pocket-fit design",
      "Smooth touch controls for music & calls",
      "Long battery backup for daily usage",
    ],
    description:
      "NeoPods keep things simple and quick. Open the case and they pair instantly. Touch controls, HD stereo sound, and a compact case that fits any pocket.",
    features: [
      "Bluetooth 5.3",
      "Instant auto-pair",
      "HD stereo sound",
      "Touch controls",
    ],
    specs: [
      ["Driver", "11mm dynamic"],
      ["Battery (buds)", "6h playback"],
      ["Battery (case)", "28h total"],
      ["Charging", "USB-C"],
      ["Weight", "4.0g per bud"],
      ["Connectivity", "Bluetooth 5.3"],
    ],
    rating: 4.5,
    reviewCount: 932,
    inStock: true,
  },
  {
    slug: "sonicbuds",
    name: "OneShot SonicBuds",
    tagline: "Bass-boosted earbuds for music lovers",
    title:
      "OneShot SonicBuds Bass Boost Wireless Earbuds, Deep Bass Sound, Bluetooth 5.3, Music Lovers Edition",
    price: 1499,
    compareAt: 2199,
    productType: "Earbuds",
    category: "Bass",
    colorName: "Graphite Black",
    colorHex: "#2a2a2a",
    imageKey: "sonicbuds",
    badge: "BASS EDITION",
    bullets: [
      "Powerful bass-enhanced audio drivers",
      "Immersive sound for music streaming",
      "Low-latency Bluetooth connection",
      "Comfortable in-ear fit for long listening",
      "Perfect for bass-heavy genres",
    ],
    description:
      "SonicBuds are tuned for listeners who love low end. Bass-enhanced drivers and a low-latency Bluetooth link deliver immersive sound for EDM, hip-hop, and bass-driven genres.",
    features: [
      "Bass-boost drivers",
      "Low-latency mode",
      "Bluetooth 5.3",
      "Dual-mic calls",
    ],
    specs: [
      ["Driver", "13mm bass-tuned"],
      ["Battery (buds)", "6h playback"],
      ["Battery (case)", "30h total"],
      ["Charging", "USB-C"],
      ["Weight", "4.5g per bud"],
      ["Latency", "Low-latency mode"],
    ],
    rating: 4.5,
    reviewCount: 718,
    inStock: true,
  },
  {
    slug: "pulsepods",
    name: "OneShot PulsePods",
    tagline: "Sport earbuds with secure fit and sweat resistance",
    title:
      "OneShot PulsePods Sports Wireless Earbuds, Sweat Resistant, Secure Fit, Ideal for Gym & Running",
    price: 1699,
    compareAt: 2499,
    productType: "Earbuds",
    category: "Sports",
    colorName: "Volt Green",
    colorHex: "#3a8a4a",
    imageKey: "pulsepods",
    badge: "SPORTS",
    bullets: [
      "Sweat and splash resistant design",
      "Secure fit for sports and workouts",
      "Stable Bluetooth connectivity during movement",
      "Lightweight build for active lifestyle",
      "Long battery life for training sessions",
    ],
    description:
      "PulsePods stay put. A secure-fit design and sweat resistance keep them locked in through runs, gym sets, and HIIT sessions, with a stable wireless link that does not drop when you move.",
    features: [
      "IPX5 sweat resistance",
      "Secure-fit ear hooks",
      "Bluetooth 5.3",
      "Voice assistant",
    ],
    specs: [
      ["Driver", "11mm dynamic"],
      ["Battery (buds)", "7h playback"],
      ["Battery (case)", "32h total"],
      ["Charging", "USB-C"],
      ["Weight", "4.8g per bud"],
      ["Water resistance", "IPX5"],
    ],
    rating: 4.4,
    reviewCount: 556,
    inStock: true,
  },
  {
    slug: "echobuds",
    name: "OneShot EchoBuds",
    tagline: "Calling earbuds with noise reduction",
    title:
      "OneShot EchoBuds Calling Earbuds with Noise Reduction, HD Voice, Wireless Bluetooth 5.3, Clear Calls",
    price: 1799,
    compareAt: 2599,
    productType: "Earbuds",
    category: "Calling",
    colorName: "Studio Silver",
    colorHex: "#c8c8c8",
    imageKey: "echobuds",
    badge: "FOR CALLS",
    bullets: [
      "Noise reduction for clearer voice calls",
      "HD microphone for meetings & communication",
      "Stable wireless performance",
      "Comfortable all-day wear design",
      "Ideal for office & work-from-home users",
    ],
    description:
      "EchoBuds are made for talk. ENC microphones isolate your voice from background noise so calls and meetings come through clearly, whether you are in an office or working from home.",
    features: [
      "ENC noise reduction",
      "Dual HD mics",
      "Bluetooth 5.3",
      "All-day comfort",
    ],
    specs: [
      ["Driver", "11mm dynamic"],
      ["Battery (buds)", "7h playback"],
      ["Battery (case)", "32h total"],
      ["Charging", "USB-C"],
      ["Weight", "4.3g per bud"],
      ["Mic", "Dual-mic ENC"],
    ],
    rating: 4.6,
    reviewCount: 642,
    inStock: true,
  },
  {
    slug: "wavepods",
    name: "OneShot WavePods",
    tagline: "Water-resistant travel-ready earbuds",
    title:
      "OneShot WavePods Waterproof Wireless Earbuds, IPX Water Resistant, Travel Ready Bluetooth Earbuds",
    price: 1899,
    compareAt: 2799,
    productType: "Earbuds",
    category: "Sports",
    colorName: "Coastal Blue",
    colorHex: "#3a6a9a",
    imageKey: "wavepods",
    bullets: [
      "Water-resistant build for outdoor use",
      "Stable connection for travel & commute",
      "Balanced sound quality for all genres",
      "Lightweight and durable design",
      "Long-lasting battery performance",
    ],
    description:
      "WavePods are built for movement and weather. A water-resistant shell, stable wireless connection, and balanced tuning make them a reliable travel and outdoor companion.",
    features: [
      "IPX6 water resistance",
      "Bluetooth 5.3",
      "Balanced tuning",
      "Travel-ready case",
    ],
    specs: [
      ["Driver", "12mm dynamic"],
      ["Battery (buds)", "8h playback"],
      ["Battery (case)", "36h total"],
      ["Charging", "USB-C"],
      ["Weight", "4.6g per bud"],
      ["Water resistance", "IPX6"],
    ],
    rating: 4.5,
    reviewCount: 421,
    inStock: true,
  },
  {
    slug: "zenbuds",
    name: "OneShot ZenBuds",
    tagline: "Noise-isolating earbuds for focus and calm",
    title:
      "OneShot ZenBuds Noise Isolating Wireless Earbuds, Relaxing Sound Profile, Focus & Meditation Earbuds",
    price: 2199,
    compareAt: 2999,
    productType: "Earbuds",
    category: "Focus",
    colorName: "Sandstone Beige",
    colorHex: "#c8b89a",
    imageKey: "zenbuds",
    bullets: [
      "Passive noise isolation for focus",
      "Soft, balanced sound tuning",
      "Comfortable fit for long sessions",
      "Ideal for meditation & study",
      "Smooth touch controls",
    ],
    description:
      "ZenBuds are tuned for calm. Passive noise isolation and a soft, balanced sound profile help you focus, study, or unwind without distractions.",
    features: [
      "Passive noise isolation",
      "Soft sound tuning",
      "Bluetooth 5.3",
      "Long-session comfort",
    ],
    specs: [
      ["Driver", "10mm balanced"],
      ["Battery (buds)", "7h playback"],
      ["Battery (case)", "32h total"],
      ["Charging", "USB-C"],
      ["Weight", "4.1g per bud"],
      ["Isolation", "Passive -24dB"],
    ],
    rating: 4.5,
    reviewCount: 318,
    inStock: true,
  },
  {
    slug: "maxtune",
    name: "OneShot MaxTune",
    tagline: "Premium earbuds with high bass drivers",
    title:
      "OneShot MaxTune Premium Wireless Earbuds, High Bass Drivers, HD Sound Quality, Bluetooth 5.3",
    price: 2499,
    compareAt: 3499,
    productType: "Earbuds",
    category: "Premium",
    colorName: "Titanium Grey",
    colorHex: "#8a8a8a",
    imageKey: "maxtune",
    badge: "PREMIUM",
    bullets: [
      "High-performance audio drivers",
      "Rich bass with clear treble balance",
      "Lag-free Bluetooth connectivity",
      "Premium build quality",
      "Ideal for audiophiles",
    ],
    description:
      "MaxTune is built for listeners who want more. High-performance drivers deliver rich bass with clean treble, while a premium shell and lag-free wireless link round out the experience.",
    features: [
      "High-performance drivers",
      "Lag-free Bluetooth 5.3",
      "Premium build",
      "Dual-mic calls",
    ],
    specs: [
      ["Driver", "14mm hi-perf"],
      ["Battery (buds)", "8h playback"],
      ["Battery (case)", "36h total"],
      ["Charging", "USB-C + Qi"],
      ["Weight", "4.7g per bud"],
      ["Codec", "AAC + SBC"],
    ],
    rating: 4.7,
    reviewCount: 287,
    inStock: true,
  },
  {
    slug: "aeropods",
    name: "OneShot AeroPods",
    tagline: "Ultra-light earbuds with a premium finish",
    title:
      "OneShot AeroPods Stylish Wireless Earbuds, Ultra Light Design, Premium Finish, Bluetooth 5.3 Earbuds",
    price: 2699,
    compareAt: 3699,
    productType: "Earbuds",
    category: "Premium",
    colorName: "Rose Gold",
    colorHex: "#c89a8a",
    imageKey: "aeropods",
    badge: "NEW RELEASE",
    bullets: [
      "Sleek and modern aesthetic design",
      "Ultra-lightweight for comfort",
      "Smooth touch controls",
      "Stable connection for daily use",
      "Premium carry case included",
    ],
    description:
      "AeroPods pair an ultra-light build with a premium finish. A sleek shell, smooth touch controls, and a stable wireless link make them a refined everyday companion.",
    features: [
      "Ultra-light 3.8g build",
      "Bluetooth 5.3",
      "Premium carry case",
      "Touch controls",
    ],
    specs: [
      ["Driver", "11mm dynamic"],
      ["Battery (buds)", "7h playback"],
      ["Battery (case)", "32h total"],
      ["Charging", "USB-C + Qi"],
      ["Weight", "3.8g per bud"],
      ["Codec", "AAC + SBC"],
    ],
    rating: 4.6,
    reviewCount: 196,
    inStock: true,
  },
  {
    slug: "probeat",
    name: "OneShot ProBeat Buds",
    tagline: "ANC earbuds with deep bass and premium sound",
    title:
      "OneShot ProBeat Buds ANC Wireless Earbuds, Active Noise Cancellation, Deep Bass, Premium Sound Experience",
    price: 3299,
    compareAt: 4499,
    productType: "Earbuds",
    category: "Premium",
    colorName: "Obsidian Black",
    colorHex: "#0e0e0e",
    imageKey: "probeat",
    badge: "FLAGSHIP",
    bullets: [
      "Active Noise Cancellation (ANC) support",
      "Deep bass with immersive audio output",
      "Premium wireless performance",
      "Comfortable long-wear design",
      "Best for music & travel experience",
    ],
    description:
      "ProBeat Buds is our flagship. Active Noise Cancellation, deep bass, and premium wireless performance deliver an immersive experience for music, travel, and long listening sessions.",
    features: [
      "Active Noise Cancellation",
      "Transparency mode",
      "Bluetooth 5.3",
      "Qi wireless charging",
    ],
    specs: [
      ["Driver", "14mm hi-perf"],
      ["Battery (buds)", "8h (ANC on)"],
      ["Battery (case)", "36h total"],
      ["Charging", "USB-C + Qi"],
      ["Weight", "4.9g per bud"],
      ["ANC depth", "Up to -32dB"],
    ],
    rating: 4.8,
    reviewCount: 174,
    inStock: true,
  },

  // ===== WIRED EARPHONES =====
  {
    slug: "wirebeat-100",
    name: "OneShot WireBeat 100",
    tagline: "Wired earphones with HD sound and in-line mic",
    title:
      "OneShot WireBeat 100 Wired Earphones with HD Sound & In-Line Mic",
    price: 199,
    compareAt: 399,
    productType: "Wired Earphones",
    category: "Wired Earphones",
    colorName: "Classic Black",
    colorHex: "#1a1a1a",
    imageKey: "wirebeat-100",
    bullets: [
      "Clear stereo sound for daily use",
      "Built-in mic for calls",
      "Tangle-resistant cable",
      "Lightweight and durable",
      "Universal 3.5mm jack",
    ],
    description:
      "WireBeat 100 is your everyday wired pair. Clear stereo sound, a built-in mic for calls, and a tangle-resistant cable that lasts.",
    features: [
      "3.5mm jack",
      "In-line mic",
      "Tangle-resistant cable",
      "Universal compatibility",
    ],
    specs: [
      ["Driver", "10mm dynamic"],
      ["Connector", "3.5mm"],
      ["Cable", "1.2m tangle-resistant"],
      ["Mic", "In-line"],
      ["Weight", "14g"],
      ["Compatibility", "Universal 3.5mm"],
    ],
    rating: 4.3,
    reviewCount: 2104,
    inStock: true,
  },
  {
    slug: "wirebeat-pro",
    name: "OneShot WireBeat Pro",
    tagline: "Bass-tuned wired earphones with enhanced audio",
    title:
      "OneShot WireBeat Pro Bass Wired Earphones with Enhanced Audio",
    price: 299,
    compareAt: 599,
    productType: "Wired Earphones",
    category: "Wired Earphones",
    colorName: "Matte Black",
    colorHex: "#0e0e0e",
    imageKey: "wirebeat-pro",
    badge: "BEST VALUE",
    bullets: [
      "Deep bass tuning",
      "Noise-isolating in-ear fit",
      "Strong braided cable",
      "HD calling microphone",
      "Long-lasting build",
    ],
    description:
      "WireBeat Pro steps up with deep bass tuning, a noise-isolating fit, and a braided cable built to last. A wired pair for listeners who want more.",
    features: [
      "Deep bass tuning",
      "Braided cable",
      "Noise-isolating tips",
      "HD mic",
    ],
    specs: [
      ["Driver", "11mm bass-tuned"],
      ["Connector", "3.5mm"],
      ["Cable", "1.2m braided"],
      ["Mic", "HD in-line"],
      ["Weight", "16g"],
      ["Isolation", "Passive -20dB"],
    ],
    rating: 4.4,
    reviewCount: 1583,
    inStock: true,
  },
  {
    slug: "flexwire",
    name: "OneShot FlexWire",
    tagline: "Neckband-style wired earphones for travel",
    title: "OneShot FlexWire Neckband Style Wired Earphones",
    price: 349,
    compareAt: 699,
    productType: "Wired Earphones",
    category: "Wired Earphones",
    colorName: "Slate Black",
    colorHex: "#2a2a2a",
    imageKey: "flexwire",
    bullets: [
      "Flexible neckband design",
      "Balanced sound output",
      "Sweat-resistant cable coating",
      "Comfortable all-day wear",
      "Ideal for travel & commute",
    ],
    description:
      "FlexWire brings neckband comfort to a wired pair. A flexible band rests around your neck, with balanced sound and a sweat-resistant coating for daily commutes.",
    features: [
      "Neckband design",
      "Sweat-resistant coating",
      "Balanced sound",
      "All-day comfort",
    ],
    specs: [
      ["Driver", "10mm dynamic"],
      ["Connector", "3.5mm"],
      ["Cable", "Neckband + 0.4m drop"],
      ["Coating", "Sweat-resistant"],
      ["Weight", "22g"],
      ["Fit", "Neckband"],
    ],
    rating: 4.3,
    reviewCount: 872,
    inStock: true,
  },

  // ===== WIRED HEADPHONES =====
  {
    slug: "studiobass-h1",
    name: "OneShot StudioBass H1",
    tagline: "Wired over-ear headphones with powerful bass",
    title: "OneShot StudioBass H1 Wired Over-Ear Headphones",
    price: 799,
    compareAt: 1299,
    productType: "Wired Headphones",
    category: "Wired Headphones",
    colorName: "Studio Black",
    colorHex: "#1a1a1a",
    imageKey: "studiobass-h1",
    bullets: [
      "Powerful bass drivers",
      "Cushioned earcups",
      "Foldable design",
      "Noise isolation",
      "Ideal for music lovers",
    ],
    description:
      "StudioBass H1 delivers powerful bass through cushioned over-ear cups. A foldable wired pair tuned for long, immersive listening sessions.",
    features: [
      "Over-ear cushioned",
      "Foldable design",
      "Powerful bass",
      "Wired 3.5mm",
    ],
    specs: [
      ["Driver", "40mm bass"],
      ["Connector", "3.5mm"],
      ["Cable", "1.5m detachable"],
      ["Ear pads", "Cushioned"],
      ["Weight", "220g"],
      ["Foldable", "Yes"],
    ],
    rating: 4.4,
    reviewCount: 645,
    inStock: true,
  },
  {
    slug: "clearsound-h2",
    name: "OneShot ClearSound H2",
    tagline: "Wired headphones for calls and music",
    title:
      "OneShot ClearSound H2 Wired Headphones for Calls & Music",
    price: 999,
    compareAt: 1599,
    productType: "Wired Headphones",
    category: "Wired Headphones",
    colorName: "Silver Grey",
    colorHex: "#c8c8c8",
    imageKey: "clearsound-h2",
    bullets: [
      "Balanced audio tuning",
      "Clear voice output",
      "Adjustable headband",
      "Soft foam padding",
      "Everyday use design",
    ],
    description:
      "ClearSound H2 is tuned for balance — clear voices for calls and even sound for music. An adjustable, padded wired pair for everyday use.",
    features: [
      "Balanced tuning",
      "Adjustable headband",
      "Soft foam padding",
      "In-line mic",
    ],
    specs: [
      ["Driver", "40mm dynamic"],
      ["Connector", "3.5mm"],
      ["Cable", "1.5m with mic"],
      ["Ear pads", "Soft foam"],
      ["Weight", "210g"],
      ["Headband", "Adjustable"],
    ],
    rating: 4.4,
    reviewCount: 412,
    inStock: true,
  },
  {
    slug: "beatpro-h3",
    name: "OneShot BeatPro H3",
    tagline: "Bass-heavy wired over-ear headphones",
    title: "OneShot BeatPro H3 Bass Heavy Wired Headphones",
    price: 1299,
    compareAt: 1999,
    productType: "Wired Headphones",
    category: "Wired Headphones",
    colorName: "Matte Black",
    colorHex: "#0e0e0e",
    imageKey: "beatpro-h3",
    badge: "BASS EDITION",
    bullets: [
      "Deep bass performance",
      "Large driver units",
      "Strong build quality",
      "Long listening comfort",
      "DJ-style sound profile",
    ],
    description:
      "BeatPro H3 is built for bass. Large drivers, a sturdy build, and a DJ-style sound profile make it the pick for bass-heavy, long listening sessions.",
    features: [
      "Large 50mm drivers",
      "DJ-style tuning",
      "Sturdy build",
      "Cushioned comfort",
    ],
    specs: [
      ["Driver", "50mm bass"],
      ["Connector", "3.5mm + 6.3mm adapter"],
      ["Cable", "2m coiled"],
      ["Ear pads", "Pro cushioned"],
      ["Weight", "280g"],
      ["Profile", "DJ-style"],
    ],
    rating: 4.5,
    reviewCount: 298,
    inStock: true,
  },

  // ===== WIRELESS HEADPHONES =====
  {
    slug: "airbass-x1",
    name: "OneShot AirBass X1",
    tagline: "Wireless over-ear headphones with bass-enhanced sound",
    title:
      "OneShot AirBass X1 Wireless Over-Ear Headphones Bluetooth",
    price: 1499,
    compareAt: 2299,
    productType: "Wireless Headphones",
    category: "Wireless Headphones",
    colorName: "Carbon Black",
    colorHex: "#1a1a1a",
    imageKey: "airbass-x1",
    bullets: [
      "Wireless Bluetooth connectivity",
      "Bass-enhanced sound",
      "Foldable portable design",
      "Long battery backup",
      "Comfortable ear cushions",
    ],
    description:
      "AirBass X1 brings wireless freedom with bass-enhanced sound. A foldable, cushioned over-ear pair with long battery life for daily listening.",
    features: [
      "Bluetooth 5.2",
      "Bass-enhanced",
      "Foldable",
      "Up to 30h battery",
    ],
    specs: [
      ["Driver", "40mm bass"],
      ["Bluetooth", "5.2"],
      ["Battery", "30h playback"],
      ["Charging", "USB-C"],
      ["Weight", "240g"],
      ["Foldable", "Yes"],
    ],
    rating: 4.5,
    reviewCount: 524,
    inStock: true,
  },
  {
    slug: "neosound-h4",
    name: "OneShot NeoSound H4",
    tagline: "Wireless headphones with HD audio and memory foam",
    title:
      "OneShot NeoSound H4 Wireless Headphones with HD Audio",
    price: 1799,
    compareAt: 2599,
    productType: "Wireless Headphones",
    category: "Wireless Headphones",
    colorName: "Gunmetal Grey",
    colorHex: "#5a5a5a",
    imageKey: "neosound-h4",
    bullets: [
      "HD stereo output",
      "Stable Bluetooth connection",
      "Soft memory foam earcups",
      "Built-in mic for calls",
      "Travel-friendly design",
    ],
    description:
      "NeoSound H4 pairs HD stereo sound with memory-foam comfort. A stable wireless link and built-in mic make it a reliable travel companion.",
    features: [
      "HD stereo",
      "Memory foam earcups",
      "Bluetooth 5.3",
      "Built-in mic",
    ],
    specs: [
      ["Driver", "40mm HD"],
      ["Bluetooth", "5.3"],
      ["Battery", "32h playback"],
      ["Charging", "USB-C"],
      ["Weight", "250g"],
      ["Earcups", "Memory foam"],
    ],
    rating: 4.6,
    reviewCount: 387,
    inStock: true,
  },
  {
    slug: "maxwave-h5",
    name: "OneShot MaxWave H5",
    tagline: "Premium wireless headphones with deep bass",
    title:
      "OneShot MaxWave H5 Premium Wireless Headphones Deep Bass",
    price: 2199,
    compareAt: 3199,
    productType: "Wireless Headphones",
    category: "Wireless Headphones",
    colorName: "Obsidian Matte",
    colorHex: "#0e0e0e",
    imageKey: "maxwave-h5",
    badge: "PREMIUM",
    bullets: [
      "Powerful drivers for rich sound",
      "Extended battery life",
      "Premium matte finish",
      "Low latency mode",
      "Perfect for entertainment",
    ],
    description:
      "MaxWave H5 is our premium wireless pair. Powerful drivers, extended battery, a low-latency mode for movies, and a premium matte finish.",
    features: [
      "Low-latency mode",
      "Premium matte finish",
      "Bluetooth 5.3",
      "Up to 40h battery",
    ],
    specs: [
      ["Driver", "45mm hi-perf"],
      ["Bluetooth", "5.3"],
      ["Battery", "40h playback"],
      ["Charging", "USB-C"],
      ["Weight", "260g"],
      ["Latency", "Low-latency mode"],
    ],
    rating: 4.7,
    reviewCount: 213,
    inStock: true,
  },

  // ===== PORTABLE SPEAKERS =====
  {
    slug: "boommini-s1",
    name: "OneShot BoomMini S1",
    tagline: "Compact pocket-sized portable Bluetooth speaker",
    title:
      "OneShot BoomMini S1 Portable Bluetooth Speaker Compact Size",
    price: 599,
    compareAt: 999,
    productType: "Portable Speakers",
    category: "Portable Speakers",
    colorName: "Mini Black",
    colorHex: "#1a1a1a",
    imageKey: "boommini-s1",
    bullets: [
      "Pocket-sized speaker",
      "Loud stereo output",
      "Bluetooth connectivity",
      "Rechargeable battery",
      "Travel-friendly",
    ],
    description:
      "BoomMini S1 is a pocket-sized speaker with surprisingly loud stereo sound. Bluetooth, rechargeable, and ready to travel.",
    features: [
      "Pocket-sized",
      "Bluetooth 5.0",
      "Rechargeable",
      "Up to 6h battery",
    ],
    specs: [
      ["Driver", "5W full-range"],
      ["Bluetooth", "5.0"],
      ["Battery", "6h playback"],
      ["Charging", "USB-C"],
      ["Weight", "180g"],
      ["Size", "Pocket"],
    ],
    rating: 4.3,
    reviewCount: 1456,
    inStock: true,
  },
  {
    slug: "boombox-s2",
    name: "OneShot BoomBox S2",
    tagline: "Bluetooth speaker with deep bass and LED indicator",
    title:
      "OneShot BoomBox S2 Bluetooth Speaker with Deep Bass",
    price: 999,
    compareAt: 1599,
    productType: "Portable Speakers",
    category: "Portable Speakers",
    colorName: "Dark Grey",
    colorHex: "#3a3a3a",
    imageKey: "boombox-s2",
    bullets: [
      "Enhanced bass output",
      "Strong volume range",
      "LED indicator design",
      "Wireless connectivity",
      "Indoor & outdoor use",
    ],
    description:
      "BoomBox S2 brings enhanced bass and strong volume in a portable form. An LED indicator and rugged build make it ready for indoor and outdoor use.",
    features: [
      "Enhanced bass",
      "LED indicator",
      "Bluetooth 5.0",
      "Indoor + outdoor",
    ],
    specs: [
      ["Driver", "10W bass"],
      ["Bluetooth", "5.0"],
      ["Battery", "8h playback"],
      ["Charging", "USB-C"],
      ["Weight", "340g"],
      ["Use", "Indoor + outdoor"],
    ],
    rating: 4.4,
    reviewCount: 892,
    inStock: true,
  },
  {
    slug: "partyblast-s3",
    name: "OneShot PartyBlast S3",
    tagline: "High-volume party speaker with LED light effects",
    title:
      "OneShot PartyBlast S3 High Volume Bluetooth Party Speaker",
    price: 1499,
    compareAt: 2299,
    productType: "Portable Speakers",
    category: "Portable Speakers",
    colorName: "Party Black",
    colorHex: "#1a1a1a",
    imageKey: "partyblast-s3",
    badge: "PARTY",
    bullets: [
      "Powerful party sound",
      "Bass boost mode",
      "LED light effects",
      "Long battery backup",
      "Dual connectivity",
    ],
    description:
      "PartyBlast S3 is built for parties. High-volume output, a bass boost mode, LED light effects, and dual connectivity keep the night going.",
    features: [
      "LED light effects",
      "Bass boost mode",
      "Dual connectivity",
      "Up to 10h battery",
    ],
    specs: [
      ["Driver", "20W party"],
      ["Bluetooth", "5.0"],
      ["Battery", "10h playback"],
      ["Charging", "USB-C"],
      ["Weight", "680g"],
      ["Lights", "RGB LED"],
    ],
    rating: 4.4,
    reviewCount: 567,
    inStock: true,
  },
  {
    slug: "megaboom-s4",
    name: "OneShot MegaBoom S4",
    tagline: "Heavy bass rugged outdoor portable speaker",
    title:
      "OneShot MegaBoom S4 Heavy Bass Portable Speaker",
    price: 2199,
    compareAt: 3199,
    productType: "Portable Speakers",
    category: "Portable Speakers",
    colorName: "Rugged Black",
    colorHex: "#1a1a1a",
    imageKey: "megaboom-s4",
    bullets: [
      "Extra loud output",
      "Deep bass resonance",
      "Rugged build",
      "Outdoor ready",
      "Multi-device pairing",
    ],
    description:
      "MegaBoom S4 is our rugged outdoor speaker. Extra-loud output, deep bass, a rugged build, and multi-device pairing for any adventure.",
    features: [
      "Rugged outdoor build",
      "Multi-device pairing",
      "Extra-loud output",
      "Up to 12h battery",
    ],
    specs: [
      ["Driver", "30W heavy bass"],
      ["Bluetooth", "5.0"],
      ["Battery", "12h playback"],
      ["Charging", "USB-C"],
      ["Weight", "850g"],
      ["Build", "Rugged IPX5"],
    ],
    rating: 4.5,
    reviewCount: 342,
    inStock: true,
  },

  // ===== PREMIUM SPEAKERS =====
  {
    slug: "pulsetower-t1",
    name: "OneShot PulseTower T1",
    tagline: "Tower Bluetooth speaker with room-filling sound",
    title:
      "OneShot PulseTower T1 Tower Bluetooth Speaker Premium Sound",
    price: 2999,
    compareAt: 4299,
    productType: "Premium Speakers",
    category: "Premium Speakers",
    colorName: "Tower Black",
    colorHex: "#0e0e0e",
    imageKey: "pulsetower-t1",
    badge: "PREMIUM",
    bullets: [
      "Tower-style design",
      "Room-filling sound",
      "Deep bass system",
      "Remote control support",
      "Home entertainment focus",
    ],
    description:
      "PulseTower T1 is a tower speaker that fills the room. Deep bass, a tall profile, and remote control support make it the centrepiece of home entertainment.",
    features: [
      "Tower design",
      "Room-filling sound",
      "Remote control",
      "Deep bass system",
    ],
    specs: [
      ["Driver", "60W tower"],
      ["Bluetooth", "5.0"],
      ["Power", "AC powered"],
      ["Remote", "Included"],
      ["Weight", "3.2kg"],
      ["Profile", "Tower"],
    ],
    rating: 4.6,
    reviewCount: 184,
    inStock: true,
  },
  {
    slug: "echocube-t2",
    name: "OneShot EchoCube T2",
    tagline: "Smart compact cube speaker with balanced sound",
    title:
      "OneShot EchoCube T2 Smart Bluetooth Speaker HD Audio",
    price: 3299,
    compareAt: 4599,
    productType: "Premium Speakers",
    category: "Premium Speakers",
    colorName: "Cube Grey",
    colorHex: "#9a9a9a",
    imageKey: "echocube-t2",
    bullets: [
      "Compact cube design",
      "Clear vocals + bass balance",
      "Stable wireless streaming",
      "Modern aesthetic",
      "Indoor premium sound",
    ],
    description:
      "EchoCube T2 is a smart cube speaker with clear vocals and balanced bass. A modern aesthetic and stable streaming for premium indoor listening.",
    features: [
      "Smart cube design",
      "Balanced vocals + bass",
      "Bluetooth 5.0",
      "Modern aesthetic",
    ],
    specs: [
      ["Driver", "40W cube"],
      ["Bluetooth", "5.0"],
      ["Power", "AC powered"],
      ["Streaming", "Stable wireless"],
      ["Weight", "1.8kg"],
      ["Profile", "Cube"],
    ],
    rating: 4.6,
    reviewCount: 142,
    inStock: true,
  },
  {
    slug: "sonicbar-sb1",
    name: "OneShot SonicBar SB1",
    tagline: "Bluetooth soundbar for TV and music",
    title:
      "OneShot SonicBar SB1 Bluetooth Soundbar for TV & Music",
    price: 3999,
    compareAt: 5499,
    productType: "Premium Speakers",
    category: "Premium Speakers",
    colorName: "Bar Black",
    colorHex: "#1a1a1a",
    imageKey: "sonicbar-sb1",
    badge: "FLAGSHIP",
    bullets: [
      "Home theater soundbar",
      "Deep cinematic bass",
      "HDMI/Bluetooth support",
      "Wide soundstage",
      "TV & OTT optimized",
    ],
    description:
      "SonicBar SB1 is a home theater soundbar with deep cinematic bass, HDMI and Bluetooth support, and a wide soundstage tuned for TV and OTT.",
    features: [
      "HDMI + Bluetooth",
      "Cinematic bass",
      "Wide soundstage",
      "TV & OTT tuned",
    ],
    specs: [
      ["Output", "120W soundbar"],
      ["Inputs", "HDMI + Bluetooth + AUX"],
      ["Bluetooth", "5.0"],
      ["Power", "AC powered"],
      ["Weight", "2.4kg"],
      ["Profile", "Soundbar"],
    ],
    rating: 4.7,
    reviewCount: 96,
    inStock: true,
  },

  // ===== GAMING AUDIO =====
  {
    slug: "gamepulse-g1",
    name: "OneShot GamePulse G1",
    tagline: "Wired gaming headset with mic and strong bass",
    title:
      "OneShot GamePulse G1 Wired Gaming Headset with Mic",
    price: 999,
    compareAt: 1599,
    productType: "Gaming Audio",
    category: "Gaming Audio",
    colorName: "Gamer Black",
    colorHex: "#1a1a1a",
    imageKey: "gamepulse-g1",
    bullets: [
      "Clear voice chat",
      "Low latency audio",
      "Soft ear cushions",
      "Strong bass effects",
      "PC & mobile compatible",
    ],
    description:
      "GamePulse G1 is a wired gaming headset with clear voice chat, low-latency audio, and strong bass effects. Soft cushions keep long sessions comfortable.",
    features: [
      "Low-latency wired",
      "Boom mic",
      "RGB accent",
      "PC + mobile compatible",
    ],
    specs: [
      ["Driver", "50mm gaming"],
      ["Connector", "3.5mm + USB"],
      ["Mic", "Boom noise-isolated"],
      ["Cushions", "Soft foam"],
      ["Weight", "320g"],
      ["Compatibility", "PC + mobile"],
    ],
    rating: 4.4,
    reviewCount: 738,
    inStock: true,
  },
  {
    slug: "gamex-pro-g2",
    name: "OneShot GameX Pro G2",
    tagline: "Wireless gaming headset with surround-style audio",
    title:
      "OneShot GameX Pro G2 Wireless Gaming Headset",
    price: 1799,
    compareAt: 2599,
    productType: "Gaming Audio",
    category: "Gaming Audio",
    colorName: "Pro Black",
    colorHex: "#0e0e0e",
    imageKey: "gamex-pro-g2",
    badge: "PRO",
    bullets: [
      "Surround-style audio",
      "Noise-isolated mic",
      "Bluetooth + dongle support",
      "Long battery life",
      "Designed for gamers",
    ],
    description:
      "GameX Pro G2 is a wireless gaming headset with surround-style audio, a noise-isolated mic, and Bluetooth + dongle support. Built for long gaming sessions.",
    features: [
      "Wireless + dongle",
      "Surround-style audio",
      "Noise-isolated mic",
      "Up to 20h battery",
    ],
    specs: [
      ["Driver", "50mm surround"],
      ["Connection", "Bluetooth + 2.4GHz dongle"],
      ["Mic", "Noise-isolated boom"],
      ["Battery", "20h playback"],
      ["Weight", "340g"],
      ["Latency", "Low-latency dongle"],
    ],
    rating: 4.6,
    reviewCount: 284,
    inStock: true,
  },

  // ===== AUDIO ACCESSORIES =====
  {
    slug: "audiolink-a1",
    name: "OneShot AudioLink A1",
    tagline: "3.5mm to Type-C audio adapter",
    title:
      "OneShot AudioLink A1 3.5mm to Type-C Audio Adapter",
    price: 149,
    compareAt: 299,
    productType: "Audio Accessories",
    category: "Audio Accessories",
    colorName: "White",
    colorHex: "#f3f3f3",
    imageKey: "audiolink-a1",
    bullets: [
      "Universal compatibility",
      "Clear sound transmission",
      "Durable connector",
      "Plug & play design",
      "Compact size",
    ],
    description:
      "AudioLink A1 is a 3.5mm to Type-C adapter that lets you use wired earphones with USB-C devices. Plug-and-play, compact, and durable.",
    features: [
      "Type-C to 3.5mm",
      "Plug & play",
      "Compact",
      "Universal compatibility",
    ],
    specs: [
      ["Input", "USB Type-C"],
      ["Output", "3.5mm"],
      ["Length", "0.2m"],
      ["Setup", "Plug & play"],
      ["Weight", "8g"],
      ["DAC", "Built-in"],
    ],
    rating: 4.4,
    reviewCount: 1923,
    inStock: true,
  },
  {
    slug: "sounddock-d1",
    name: "OneShot SoundDock D1",
    tagline: "Desktop Bluetooth speaker dock",
    title:
      "OneShot SoundDock D1 Desktop Bluetooth Speaker Dock",
    price: 1299,
    compareAt: 1999,
    productType: "Audio Accessories",
    category: "Audio Accessories",
    colorName: "Desk Black",
    colorHex: "#1a1a1a",
    imageKey: "sounddock-d1",
    bullets: [
      "Desk-friendly design",
      "Balanced stereo output",
      "Bluetooth + AUX support",
      "Compact home setup",
      "Ideal for workstations",
    ],
    description:
      "SoundDock D1 is a desktop speaker dock with balanced stereo output. Bluetooth and AUX support make it a clean fit for any workstation.",
    features: [
      "Desktop dock design",
      "Bluetooth + AUX",
      "Balanced stereo",
      "Workstation-ready",
    ],
    specs: [
      ["Output", "10W stereo"],
      ["Inputs", "Bluetooth + AUX"],
      ["Power", "USB powered"],
      ["Profile", "Desktop dock"],
      ["Weight", "420g"],
      ["Use", "Workstation"],
    ],
    rating: 4.4,
    reviewCount: 376,
    inStock: true,
  },
  {
    slug: "basstube-bt1",
    name: "OneShot BassTube BT1",
    tagline: "Portable subwoofer speaker with heavy bass",
    title:
      "OneShot BassTube BT1 Portable Subwoofer Speaker",
    price: 1999,
    compareAt: 2999,
    productType: "Audio Accessories",
    category: "Audio Accessories",
    colorName: "Tube Black",
    colorHex: "#0e0e0e",
    imageKey: "basstube-bt1",
    badge: "BASS TUBE",
    bullets: [
      "Heavy bass output",
      "Deep low-frequency sound",
      "Bluetooth connectivity",
      "Party enhancement device",
      "Rugged portable design",
    ],
    description:
      "BassTube BT1 is a portable subwoofer speaker built for heavy bass. A rugged cylindrical body, deep low-end, and Bluetooth make it a party enhancer.",
    features: [
      "Subwoofer bass",
      "Rugged portable",
      "Bluetooth 5.0",
      "Party enhancer",
    ],
    specs: [
      ["Driver", "40W subwoofer"],
      ["Bluetooth", "5.0"],
      ["Battery", "8h playback"],
      ["Charging", "USB-C"],
      ["Weight", "720g"],
      ["Profile", "Cylinder sub"],
    ],
    rating: 4.5,
    reviewCount: 218,
    inStock: true,
  },
];

function toPaise(rupees: number) {
  return rupees * 100;
}

async function main() {
  console.log("Seeding OneShot catalog...");

  for (const p of products) {
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        tagline: p.tagline,
        title: p.title,
        price: toPaise(p.price),
        compareAt: p.compareAt ? toPaise(p.compareAt) : null,
        productType: p.productType,
        category: p.category,
        colorName: p.colorName,
        colorHex: p.colorHex,
        imageKey: p.imageKey,
        badge: p.badge ?? null,
        bullets: p.bullets.join("\n"),
        description: p.description,
        features: p.features.join("\n"),
        specs: p.specs.map(([k, v]) => `${k}: ${v}`).join("\n"),
        rating: p.rating,
        reviewCount: p.reviewCount,
        inStock: p.inStock,
      },
      create: {
        slug: p.slug,
        name: p.name,
        tagline: p.tagline,
        title: p.title,
        price: toPaise(p.price),
        compareAt: p.compareAt ? toPaise(p.compareAt) : null,
        productType: p.productType,
        category: p.category,
        colorName: p.colorName,
        colorHex: p.colorHex,
        imageKey: p.imageKey,
        badge: p.badge ?? null,
        bullets: p.bullets.join("\n"),
        description: p.description,
        features: p.features.join("\n"),
        specs: p.specs.map(([k, v]) => `${k}: ${v}`).join("\n"),
        rating: p.rating,
        reviewCount: p.reviewCount,
        inStock: p.inStock,
      },
    });
    console.log(`  ✓ ${p.slug} — ₹${p.price}`);
  }

  console.log(`Seeded ${products.length} products.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
